[project]
name = 'Decentralized-Microinsurance-for-Crop-Protection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.farmer-registration]
path = 'contracts/farmer-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
